apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-dev
  name: demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dev
  template:
    metadata:
      labels:
        app: spring-mvc-demo
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/common-cicd/spring-mvc-demo:latest
          imagePullPolicy: Always
          name: demo-dev
          ports:
            - containerPort: 8080
              protocol: TCP
